print("Hello! Welcome to the Joke Teller game!")
input()
print("What do you get when you cross a snowman and a vampire?")
input()
print("Frostbite!")
input()
print("What do dentists call an astronaut's cavity?")
input()
print("A black hole!")
input()
print("Knock knock!")
input()
print("Who's there?")
input()
print("Interrupting cow.")
input()
print("Interrupting cow wh", end="")
print("-MOO!")